# Generated by Django 4.2.13 on 2024-06-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_losses_alter_customuser_wins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
