# Generated by Django 4.2.13 on 2024-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_customuser_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_online',
        ),
        migrations.AddField(
            model_name='customuser',
            name='online_devices_count',
            field=models.IntegerField(default=0),
        ),
    ]
