# Generated by Django 4.2.14 on 2024-07-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sender_pfp',
            field=models.TextField(null=True),
        ),
    ]
