# Generated by Django 4.2.15 on 2024-09-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_notification_sender_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='match_id',
            field=models.IntegerField(null=True),
        ),
    ]
