# Generated by Django 4.2.15 on 2024-08-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_blocked_users_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='poubelle42@gmail.com', max_length=254, unique=True),
        ),
    ]
