# Generated by Django 4.2.16 on 2024-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_customuser_blocked_users_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_clicked',
            field=models.BooleanField(default=False),
        ),
    ]
