# Generated by Django 4.2.16 on 2024-09-26 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_message_is_clicked'),
        ('accounts', '0020_alter_customuser_email'),
    ]

    operations = [
    ]
