# Generated by Django 4.2.16 on 2024-09-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_customuser_matchmaking_online_count'),
        ('accounts', '0021_merge_20240926_1329'),
    ]

    operations = [
    ]
