services:

        #________________________________________#
        #|                                      |#
        #|              POSTGRES                |#
        #|______________________________________|#

    postgres:
        build: ./postgre
        ports:
           - 5432:5432
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
            interval: 5s
            timeout: 3s
            retries: 3

        #________________________________________#
        #|                                      |#
        #|                NGINX                 |#
        #|______________________________________|#

    nginx:
        build: ./nginx
        ports:
            - 4343:443
        depends_on:
            - django
        restart: always

        #________________________________________#
        #|                                      |#
        #|             1,2...DJANGO!            |#
        #|______________________________________|#

    django:
        build: ./django
        ports:
            - 8000:8000
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PORT=${POSTGRES_PORT}
        depends_on:
            postgres:
               condition: service_healthy
        volumes:
        - ./django:/usr/src/app
