# Generated by Django 4.2.14 on 2024-07-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchai',
            name='winner_type',
            field=models.CharField(blank=True, choices=[('player1', 'Player 1'), ('ai', 'AI'), ('draw', 'Draw')], max_length=10, null=True),
        ),
    ]
