# Generated by Django 4.2.14 on 2024-07-23 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morpion', '0002_matchai_winner_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchai',
            name='winner_type',
        ),
    ]
