# Generated by Django 4.2.11 on 2024-04-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_match_delete_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='alias_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='user_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
