# Generated by Django 4.2.15 on 2024-08-17 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_match_player_alter_match_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
