# Generated by Django 4.2.16 on 2024-09-21 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_match_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='player',
            new_name='player1',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='user_score',
            new_name='player1_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='alias',
            new_name='player2',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='alias_score',
            new_name='player2_score',
        ),
    ]
